# Setup
title:               Let's Talk Design
tagline:             A podcast about designing things you love
url:                 http://letstalkdesign.net
# paginate:            1
baseurl:             ""
analytics_id: UA-3104942-14

# Assets
#
sass:
  sass_dir:          _sass
  style:            :compressed

collections:
    episodes:
      output: true

exclude:
  - 'docker-compose.yml'
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'README.md'

plugins:
  - 'jekyll-paginate'
  - 'jekyll-gist'

repository: Lets-Talk-Design/lets-talk-design.github.io
